include: [".htaccess", ".nojekyll"]
defaults:
  - scope:
      path: "assets/js"
    values:
      mime_type: "application/javascript"
  - scope:
      path: "assets/css"
    values:
      mime_type: "text/css" 